DROP TABLE IF EXISTS persons CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS talks CASCADE;
DROP TABLE IF EXISTS person_knows_person CASCADE;
DROP TABLE IF EXISTS person_attended_for_talk CASCADE;
DROP TABLE IF EXISTS person_rated_talk CASCADE;
